### ISSUE TITLE
npm install | throwing node-gyp + build error

### ISSUE THREAD

**Issue by ivarreukers** [marcoturi/ionic-es6-boilerplate#1]
After cloning this repo and running (even after updating npm && node-gyp) I first had to manually install `gulp-cordova-bump` since my `npm install` was failing there. 

Now when I run `npm install` I get this output

```
c:\users\ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\nan\nan_new.h(214): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data (..\src\xml_document.cc) [C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\xmljs.vcxproj]
          ..\src\xml_document.cc(114) : see reference to function template instantiation 'v8::MaybeLocal<v8::String> Nan::New<v8::String,const char*,size_t>(A0,A1)' being compiled
          with
          [
              A0=const char *
  ,            A1=size_t
          ]
  xml_text.cc
  xml_xpath_context.cc
  win_delay_load_hook.cc
c:\users\ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\nan\nan_new.h(214): warning C4244: 'argument' : conversion from '__int64' to 'int', possible loss of data (..\src\xml_sax_parser.cc) [C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\xmljs.vcxproj]
          ..\src\xml_sax_parser.cc(254) : see reference to function template instantiation 'v8::MaybeLocal<v8::String> Nan::New<v8::String,const char*,__int64>(A0,A1)' being compiled
          with
          [
              A0=const char *
  ,            A1=__int64
          ]
c:\users\ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\nan\nan_new.h(214): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data (..\src\xml_syntax_error.cc) [C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\xmljs.vcxproj]
          ..\src\xml_syntax_error.cc(15) : see reference to function template instantiation 'v8::MaybeLocal<v8::String> Nan::New<v8::String,const char*,size_t>(A0,A1)' being compiled
          with
          [
              A0=const char *
  ,            A1=size_t
          ]
     Creating library C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\Release\xmljs.lib and object C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\Release\xmljs.exp
libxml.lib(parser.obj) : error LNK2001: unresolved external symbol snprintf [C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\xmljs.vcxproj]
C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\Release\xmljs.node : fatal error LNK1120: 1 unresolved externals [C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs\build\xmljs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ivar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ivar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ivar\documents\school\stage\workspace\v2\ionic-es6-boilerplate\node_modules\libxmljs
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ivar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.


```

**Comment by marcoturi** [comment]
@ivaro18, i think you are referring to the wrong project. The one you are looking is https://github.com/marcoturi/ionic2-boilerplate Please read carefully the part about Windows in the readme.

I corrected the links in the other threads.

**Comment by ivarreukers** [comment]
Ah, you referred this one on the Unit Test issue of ionic..
